---
version: '3.8'
services:
  flyway:
    image: 'flyway/flyway:7.3.1'
    container_name: 'niki_flyway'
    restart: 'no'
    volumes:
      - './db/flyway_data/sql:/flyway/sql'
      - './db/flyway_data/conf:/flyway/conf'
    networks:
      - 'default'
    profiles: ['tool']

  web:
    image: 'niki_web'
    build:
      context: '.'
    container_name: 'niki_web'
    hostname: 'niki_web'
    environment:
      DATABASE_HOST: 'db'
    restart: 'always'
    ports:
      - '8888:8888'
      # To protect your diary, please replace with this line and protect using reverse proxy.
      # Please read README.md for more details.
      #- '127.0.0.1:8888:8888'
    networks:
      - 'default'

  db:
    image: 'postgres:13-alpine'
    container_name: 'niki_db'
    hostname: 'niki_db'
    user: "${UID}:${GID}"
    restart: always
    environment:
      POSTGRES_DB: 'niki'
      POSTGRES_USER: 'niki'
      POSTGRES_PASSWORD: 'niki'
      POSTGRES_INITDB_ARGS: '--encoding=UTF8'
      TZ: 'Asia/Tokyo'
      PGTZ: 'Asia/Tokyo'
    expose:
      - '5432'
    volumes:
      - './var/psql:/var/lib/postgresql/data:z'
      - './db/helpers:/helpers'
    networks:
      - 'default'
    tty: true
    stdin_open: true

networks:
  default:
    external: false

