---
version: '3.7'
services:
  flyway:
    image: 'flyway/flyway:7.3.1'
    container_name: 'niki_flyway'
    restart: 'no'
    volumes:
      - ./db/flyway_data/sql:/flyway/sql
      - ./db/flyway_data/conf:/flyway/conf
    networks:
      - 'default'

  db:
    image: 'postgres:alpine'
    container_name: 'niki_db'
    hostname: 'niki_db'
    user: "${UID}:${GID}"
    environment:
      POSTGRES_DB: 'niki'
      POSTGRES_USER: 'niki'
      POSTGRES_PASSWORD: 'niki'
      POSTGRES_INITDB_ARGS: '--encoding=UTF8'
      TZ: 'Asia/Tokyo'
      PGTZ: 'Asia/Tokyo'
    expose:
      - '5432'
    ports:
      - '5432:5432'
    volumes:
      - './var/psql:/var/lib/postgresql/data:z'
      - './db/helpers:/helpers'
      - '/etc/passwd:/etc/passwd:ro'
    networks:
      - 'default'
    tty: true
    stdin_open: true

networks:
  default:
    external: false
