#!/usr/bin/env bash

set -eu
set -o pipefail

REPO_DIR="$(cd "$(dirname "$(readlink -f "$0")")" && cd .. && pwd)"
cd "${REPO_DIR}"

docker-compose run \
  --rm \
  "--user=$(id -u $USER):$(id -g $USER)" \
  db \
  mysql '--protocol=tcp' \
        '--user=niki' '--password=niki' \
        '--host=db' '--database=niki' \
        '--default-character-set=utf8mb4' \
        "$@"
