#!/usr/bin/env bash

set -eu
set -o pipefail

REPO_DIR="$(cd "$(dirname "$(readlink -f "$0")")" && cd .. && pwd)"
cd "${REPO_DIR}"

UID=$(id -u "${UID}") GID=$(id -g "${UID}") docker-compose run \
  --rm \
  db \
  mysql '--protocol=tcp' \
        '--user=niki' '--password=niki' \
        '--host=db' '--database=niki' \
        '--default-character-set=utf8mb4' \
        "$@"
