#!/usr/bin/env bash

set -eu
set -o pipefail

REPO_DIR="$(cd "$(dirname "$(readlink -f "$0")")" && cd .. && pwd)"
cd "${REPO_DIR}"

UID=$(id -u "${UID}") GID=$(id -g "${UID}") docker-compose run \
  --rm \
  db \
  mysqldump '--protocol=tcp' \
            '--user=root' '--password=root' \
            '--host=db' \
            '--default-character-set=utf8mb4' \
            "$@" '--databases' 'niki'
